### ISSUE TITLE
Use RecyclerView

### ISSUE THREAD

**Issue by masoudfcr** [klinker41/android-slidingactivity#19]
When I'm trying to use a RecyclerView inside a SlidingActivity I get this error:

         Caused by: java.lang.ClassNotFoundException: android.view.RecyclerView
           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
           at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
           at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
           at android.view.LayoutInflater.createView(LayoutInflater.java:552)
           at android.view.LayoutInflater.onCreateView(LayoutInflater.java:643)
                                

I added library project to my project and I tried adding recyclerview gradle dependency but I get the same error. 
how can I fix it?

**Comment by masoudfcr** [comment]
I found the answer....
it have to be like:

            <android.support.v7.widget.RecyclerView
not 

            <RecyclerView

in the layout!
