### ISSUE TITLE
Crash when opening SlidingActivity from Widget

### ISSUE THREAD

**Issue by jlelse** [klinker41/android-slidingactivity#2]
This only happens when the app isn't active.
I did everything like in the ReadMe and I'm opening the activity from the widget via a PendingIntent.
Do I have to add sth special to the Intent, do I have to change something in the Manifest or what did I wrong?

**Comment by klinker41** [comment]
It is working correctly from the widget in Talon, so this should not be a
problem. If you can post a stack trace then we can see what the issue is.

**Comment by jlelse** [comment]
@klinker41 Here is the stack trace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{jlelse.readit.debug/jlelse.readit.activities.SlidingReadActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.klinker.android.sliding.SlidingActivity.setTitle(SlidingActivity.java:183)
            at jlelse.readit.activities.SlidingReadActivity.init(SlidingReadActivity.java:78)
            at com.klinker.android.sliding.SlidingActivity.onCreate(SlidingActivity.java:165)
            at android.app.Activity.performCreate(Activity.java:5248)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jlelse** [comment]
@klinker41 Oh sorry it's my fault! I did something else wrong!
But thanks for this great library and the fast support!
