### ISSUE TITLE
Cannot start this animator on a detached view

### ISSUE THREAD

**Issue by VictorBG** [klinker41/android-slidingactivity#20]
When I open the activity from a RecyclerView works ok, but when I open it again with the same image drops an IllegalStateException. I add the Logcat: 

```
 Caused by: java.lang.IllegalStateException: Cannot start this animator on a detached view!
at android.view.RenderNode.addAnimator(RenderNode.java:817)
at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:53)
at com.klinker.android.sliding.SlidingActivity.setImage(SlidingActivity.java:345)
at com.vvss.noticiasanime.DetailNewDark$2$override.onResourceReady(DetailNewDark.java:129)
at com.vvss.noticiasanime.DetailNewDark$2$override.access$dispatch(DetailNewDark.java)
at com.vvss.noticiasanime.DetailNewDark$2.onResourceReady(DetailNewDark.java:0)
at com.vvss.noticiasanime.DetailNewDark$2.onResourceReady(DetailNewDark.java:126)
at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
```

I add my code: 
```
target = new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                setImage(resource);           
            }
        };

```

Seems that the problem is in the `setImage()` :

```
public void setImage(Bitmap bitmap) {

        photoView.setImageBitmap(bitmap);

        if (isStarting) {
            Palette palette = Palette.from(bitmap).generate();
            setPrimaryColors(palette.getVibrantColor(DEFAULT_PRIMARY_COLOR),
                    palette.getDarkVibrantColor(DEFAULT_PRIMARY_DARK_COLOR));
        } else {
            photoViewTempBackground.setBackgroundDrawable(photoView.getBackground());
            photoViewTempBackground.setVisibility(View.VISIBLE);

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                final int cx = (int) photoView.getX() + photoView.getMeasuredWidth() / 2;
                final int cy = (int) photoView.getY() + photoView.getMeasuredHeight() / 2;
                final int finalRadius = photoView.getWidth();


                Animator anim = ViewAnimationUtils.createCircularReveal(photoView, cx, cy,
                        0, finalRadius);
                anim.setDuration(500);
                anim.addListener(new AnimatorListenerAdapter() {
                    @Override
                    public void onAnimationEnd(Animator animation) {
                        super.onAnimationEnd(animation);
                        photoViewTempBackground.setVisibility(View.GONE);
                    }
                });
                anim.start();


            } else {
                photoView.setAlpha(0f);
                photoView.animate()
                        .alpha(1f)
                        .setListener(new AnimatorListenerAdapter() {
                            @Override
                            public void onAnimationEnd(Animator animation) {
                                super.onAnimationEnd(animation);
                                photoView.setAlpha(1f);
                                photoViewTempBackground.setVisibility(View.GONE);
                            }
                        })
                        .start();
            }
        }
    }
```

Specially in the line `  Animator anim = ViewAnimationUtils.createCircularReveal(photoView, cx, cy,
                        0, finalRadius);`. How can I solve it? Thanks.

**Comment by klinker24** [comment]
Not really sure about your code to know why it would be happening, but looks like it is trying to use an old instance of the header photo `ImageView`.

It is pretty easy to bypass the `setImage()` usage, you could just do:

```java
Glide.with(context)
        .load(photoUri)
        .into((ImageView) findViewById(R.id.photo));
```

**Comment by CHRehan** [comment]
Check your Layout is attached to window or not by using r`ootLayout.isAttachedToWindow()` method.

```
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        if (rootLayout!= null) {

            if(rootLayout.isAttachedToWindow()) {
                ViewTreeObserver viewTreeObserver = drawerLayout.getViewTreeObserver();
                if (viewTreeObserver.isAlive()) {
                    viewTreeObserver.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                        @Override
                        public void onGlobalLayout() {
                            startRevealAnimation(rootLayout);
                            rootLayout.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        }
                    });
                }
            }
        }
```
