### ISSUE TITLE
Crash while inflating XML

### ISSUE THREAD

**Issue by seasonyuu** [klinker41/android-slidingactivity#46]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.seasonyuu.douban.movie/me.seasonyuu.douban.movie.ui.ViewMovieActivity}: android.view.InflateException: Binary XML file line #51: Binary XML file line #18: Error inflating class com.klinker.android.sliding.TouchlessScrollView
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2760)
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2846)
             at android.app.ActivityThread.-wrap12(ActivityThread.java)
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
             at android.os.Handler.dispatchMessage(Handler.java:102)
             at android.os.Looper.loop(Looper.java:154)
             at android.app.ActivityThread.main(ActivityThread.java:6322)
             at java.lang.reflect.Method.invoke(Native Method)
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
          Caused by: android.view.InflateException: Binary XML file line #51: Binary XML file line #18: Error inflating class com.klinker.android.sliding.TouchlessScrollView
          Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.klinker.android.sliding.TouchlessScrollView
          Caused by: java.lang.reflect.InvocationTargetException
             at java.lang.reflect.Constructor.newInstance0(Native Method)
             at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
             at android.view.LayoutInflater.createView(LayoutInflater.java:645)
             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
             at android.view.LayoutInflater.parseInclude(LayoutInflater.java:964)
             at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
             at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
             at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
             at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
             at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
             at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
             at com.klinker.android.sliding.SlidingActivity.onCreate(SlidingActivity.java:107)
             at android.app.Activity.performCreate(Activity.java:6760)
             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2713)
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2846)
             at android.app.ActivityThread.-wrap12(ActivityThread.java)
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
             at android.os.Handler.dispatchMessage(Handler.java:102)
             at android.os.Looper.loop(Looper.java:154)
             at android.app.ActivityThread.main(ActivityThread.java:6322)
             at java.lang.reflect.Method.invoke(Native Method)
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
          Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f03007c a=-1}
             at android.content.res.TypedArray.getDrawable(TypedArray.java:925)
             at android.view.View.<init>(View.java:4213)
             at android.view.ViewGroup.<init>(ViewGroup.java:579)
             at android.widget.FrameLayout.<init>(FrameLayout.java:92)
             at android.widget.ScrollView.<init>(ScrollView.java:184)
             at android.widget.ScrollView.<init>(ScrollView.java:180)
             at com.klinker.android.sliding.TouchlessScrollView.<init>(TouchlessScrollView.java:57)
E/AndroidRuntime:     at com.klinker.android.sliding.TouchlessScrollView.<init>(TouchlessScrollView.java:47)
                                                                               	... 29 more
```

    compileSdkVersion 25
    buildToolsVersion "25.0.3"

    implementation 'com.android.support:appcompat-v7:25.4.0'

Code of Activity
```kotlin
class ViewMovieActivity : SlidingActivity() {

    override fun init(savedInstanceState: Bundle?) {
        setContent(R.layout.activity_view_movie)
    }
}
```

**Comment by klinker24** [comment]
Does the sample app run ok?

**Comment by seasonyuu** [comment]
NO, but when I romove these code in this (layout)[https://github.com/klinker41/android-slidingactivity/blob/master/library/src/main/res/layout/sliding_content.xml], the problem solved.

```xml
android:foreground="?content_background">
```
